apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlWorkbench.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.mysqlWorkbench.deployment.name }}
  type: {{ .Values.mysqlWorkbench.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysqlWorkbench.service.port }}
      targetPort: {{ .Values.mysqlWorkbench.service.targetPort }}
      nodePort: {{ .Values.mysqlWorkbench.service.nodePort }}
      
