apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nodeapp.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.nodeapp.deployment.replicas }}
  selector:
    matchLabels:
      app: nodeapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        date: '{{ now | date "2006-01-02T15:04:05Z07:00" }}'
      labels:
        app: nodeapp
    spec:
      imagePullSecrets:
        - name: {{ .Values.nodeapp.imagePullSecret }}
      containers:
        - name: nodeapp
          image: "{{ .Values.nodeapp.deployment.image }}:{{ .Values.nodeapp.deployment.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.nodeapp.deployment.containerPort }}
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_HOST
            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DIALECT