apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeapp.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: {{ .Values.nodeapp.service.port }}
      targetPort: {{ .Values.nodeapp.service.targetPort }}
