apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-workbench
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-workbench
  template:
    metadata:
      labels:
        app: mysql-workbench
    spec:
      containers:
        - name: mysql-workbench
          image: linuxserver/mysql-workbench
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:  
                configMapKeyRef:  
                  name: mysql-config
                  key: MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-workbench-service
  namespace: my-namespace
spec:
  selector:
    app: mysql-workbench
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
