apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: nodeapp
          image: 781104868468.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_HOST
            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DIALECT
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: my-namespace
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
